name: Monitor KRS via Web3

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest
    env:
      TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      ARBITRUM_RPC_URL: ${{ secrets.ARBITRUM_RPC_URL }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install requests web3 python-dotenv

      - name: Run monitor
        run: python monitor.py

      - name: Commit kursy.json i kursy_doba.json
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add kursy.json kursy_doba.json
          git commit -m "Auto update kursów z monitora" || echo "Brak zmian"
          git push
