name: Monitor kursów KRS

on:
  schedule:
    - cron: "*/10 * * * *"  # co 10 minut
  workflow_dispatch:        # możliwość ręcznego odpalenia

jobs:
  monitor:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install web3

      - name: Run monitor script
        run: python monitor.py

      - name: Commit updated kursy.json
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add kursy.json kursy_doba.json
          git commit -m "Auto update kursów" || echo "No changes"
          git push
